# Generated by Django 2.2.7 on 2019-11-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20191128_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
